apiVersion: apps/v1
kind: Deployment
metadata:
  name: noise-app
  labels:
    component: noise-app
    role: generator
spec:
  replicas: 1
  selector:
    matchLabels:
      component: noise-app
      role: generator
  template:
    metadata:
      labels:
        component: noise-app
        role: generator
    spec:
      containers:
      - name: noise-app
        image: busybox:1.27.2
        command:
        - "/bin/sh"
        - "-ec"
        - "while :; do echo $(date --utc +%FT%TZ) INFO $(head -c 16 /dev/urandom | md5sum | head -c 32); sleep 5 ; done"
        resources:
          requests:
            cpu: "50m"
            memory: "100Mi"
          limits:
            cpu: "50m"
            memory: "100Mi"
        volumeMounts:
        - mountPath: /usr/share/logstash/config
          name: logstash-configmap
      volumes:
      - configMap:
          name: logstash-configmap
        name: logstash-configmap